server:
    port: 8002

spring:
    datasource:
        username: root
        password: 061966
        url: jdbc:mysql://121.36.206.19:3306/prototype?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-test-query: select 1
            connection-timeout: 20000
            maximum-pool-size: 5
            minimum-idle: 5



    kafka:
        bootstrap-servers: 121.36.206.19:9094
        consumer:
            group-id: websocket-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.ByteArraySerializer
            enable-auto-commit: false
            auto-offset-reset: latest

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
#            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
